server:
  port: 8081

jiudlogger:
  isopen: true
  split: "*********"
  suffix: "++++"
  postfix: "++++"
  system: mhzx
 # showinfo: requestTime,requestUrl,description,requestMethod,classMethod

logging:
  file:
    path: logs/report
